import { createElement } from 'lwc';
import PokeList from 'c/pokeList';

describe('c-poke-list', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });
    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-poke-list', {
            is: PokeList
        });
        document.body.appendChild(element);
        expect(1).toBe(1);
    });
});